export const APP_LOAD = 'APP_LOAD';
export const APP_USER = 'APP_USER';
export const APP_REDIRECT = 'APP_REDIRECT';
export const APP_SET_LOCATION = 'APP_SET_LOCATION';
export const APP_SET_TITLE = 'APP_SET_TITLE';

export const APP_LOGIN = 'APP_LOGIN';
export const APP_LOGIN_UNLOAD = 'APP_LOGIN_UNLOAD';
export const APP_CHANGE_PASSWORD = 'APP_CHANGE_PASSWORD';
export const APP_RESET_PASSWORD = 'APP_RESET_PASSWORD';
export const APP_LOGOUT = 'APP_LOGOUT';
export const APP_LOGIN_SSO = 'APP_LOGIN_SSO';

export const API_START = 'API_START';
export const API_END = 'API_END';
export const API_CANCEL = 'API_CANCEL';

export const TESTING_LOAD = 'TESTING_LOAD';
export const TESTING_UNLOAD = 'TESTING_UNLOAD';
export const TESTING_SINGLE_LOAD = 'TESTING_SINGLE_LOAD';
export const TESTING_CREATE = 'TESTING_CREATE';
export const TESTING_REMOVE = 'TESTING_REMOVE';

export const ORDER_LIST_LOAD = 'ORDER_LIST_LOAD';
export const ORDER_SINGLE_LOAD = 'ORDER_SINGLE_LOAD';
export const ORDER_SINGLE_UNLOAD = 'ORDER_SINGLE_UNLOAD';
export const ORDER_UNLOAD = 'ORDER_UNLOAD';
export const ORDER_SUMMARY = 'ORDER_SUMMARY';
export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_UPDATE = 'ORDER_UPDATE';
export const ORDER_COMMAND = 'ORDER_COMMAND';
export const ORDER_UTILIZATION_LOAD = 'ORDER_UTILIZATION_LOAD';
export const ORDER_UTILIZATION_UNLOAD = 'ORDER_UTILIZATION_UNLOAD';

export const USER_LIST_LOAD = 'USER_LIST_LOAD';
export const USER_SINGLE_LOAD = 'USER_SINGLE_LOAD';
export const USER_CREATE = 'USER_CREATE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_REMOVE = 'USER_REMOVE';
export const USER_UNLOAD = 'USER_UNLOAD';
export const USER_SEARCH = 'USER_SEARCH';

export const COMPANY_LIST_LOAD = 'COMPANY_LIST_LOAD';
export const COMPANY_SINGLE_LOAD = 'COMPANY_SINGLE_LOAD';
export const COMPANY_CREATE = 'COMPANY_CREATE';
export const COMPANY_UPDATE = 'COMPANY_UPDATE';
export const COMPANY_REMOVE = 'COMPANY_REMOVE';
export const COMPANY_UNLOAD = 'COMPANY_UNLOAD';

export const DIVISION_LIST_LOAD = 'DIVISION_LIST_LOAD';
export const DIVISION_SINGLE_LOAD = 'DIVISION_SINGLE_LOAD';
export const DIVISION_CREATE = 'DIVISION_CREATE';
export const DIVISION_UPDATE = 'DIVISION_UPDATE';
export const DIVISION_REMOVE = 'DIVISION_REMOVE';
export const DIVISION_UNLOAD = 'DIVISION_UNLOAD';

export const POOL_LIST_LOAD = 'POOL_LIST_LOAD';
export const POOL_SINGLE_LOAD = 'POOL_SINGLE_LOAD';
export const POOL_CREATE = 'POOL_CREATE';
export const POOL_UPDATE = 'POOL_UPDATE';
export const POOL_REMOVE = 'POOL_REMOVE';
export const POOL_UNLOAD = 'POOL_UNLOAD';

export const FLEET_LIST_LOAD = 'FLEET_LIST_LOAD';
export const FLEET_LIST_KEYS = 'FLEET_LIST_KEYS';
export const FLEET_LIST_FILTER = 'FLEET_LIST_FILTER';
export const FLEET_SINGLE_LOAD = 'FLEET_SINGLE_LOAD';
export const FLEET_ANALYSIS = 'FLEET_ANALYSIS';
export const FLEET_ANALYSIS1 = 'FLEET_ANALYSIS1';
export const FLEET_UTILIZATION = 'FLEET_UTILIZATION';
export const FLEET_ANALYSIS_DETAIL = 'FLEET_ANALYSIS_DETAIL';
export const FLEET_CREATE = 'FLEET_CREATE';
export const FLEET_UPDATE = 'FLEET_UPDATE';
export const FLEET_REMOVE = 'FLEET_REMOVE';
export const FLEET_UNLOAD = 'FLEET_UNLOAD';
export const FLEET_HISTORY_LOAD = 'FLEET_HISTORY_LOAD';

export const FLEET_REPORT_LIST_LOAD = 'FLEET_REPORT_LIST_LOAD';
export const FLEET_REPORT_SINGLE_LOAD = 'FLEET_REPORT_SINGLE_LOAD';
export const FLEET_REPORT_CREATE = 'FLEET_REPORT_CREATE';
export const FLEET_REPORT_UPDATE = 'FLEET_REPORT_UPDATE';
export const FLEET_REPORT_REMOVE = 'FLEET_REPORT_REMOVE';
export const FLEET_REPORT_UNLOAD = 'FLEET_REPORT_UNLOAD';
export const FLEET_REPORT_SINGLE_UNLOAD = 'FLEET_REPORT_SINGLE_UNLOAD';

export const MINILIST_COMPANY_LOAD = 'MINILIST_COMPANY_LOAD';
export const MINILIST_COMPANY_UNLOAD = 'MINILIST_COMPANY_UNLOAD';
export const MINILIST_DIVISION_LOAD = 'MINILIST_DIVISION_LOAD';
export const MINILIST_DIVISION_UNLOAD = 'MINILIST_DIVISION_UNLOAD';
export const MINILIST_POOL_LOAD = 'MINILIST_POOL_LOAD';
export const MINILIST_POOL_UNLOAD = 'MINILIST_POOL_UNLOAD';
export const MINILIST_FLEET_LOAD = 'MINILIST_FLEET_LOAD';
export const MINILIST_FLEET_UNLOAD = 'MINILIST_FLEET_UNLOAD';

export const NOTIFICATION_LONG_LOAD = 'NOTIFICATION_LONG_LOAD';
export const NOTIFICATION_LONG_UNLOAD = 'NOTIFICATION_LONG_UNLOAD';
export const NOTIFICATION_SHORT_LOAD = 'NOTIFICATION_SHORT_LOAD';
export const NOTIFICATION_SHORT_UNLOAD = 'NOTIFICATION_SHORT_UNLOAD';
export const NOTIFICATION_READ = 'NOTIFICATION_READ';

export const SEARCH_LOAD = 'SEARCH_LOAD';
export const SEARCH_UNLOAD = 'SEARCH_UNLOAD';

export const CHAT_LOAD = 'CHAT_LOAD';
export const CHAT_UNLOAD = 'CHAT_UNLOAD';
